export const properties = {
  structure: [
    "name", "values", "initial", "applies", "inherited", "percentages", "media",
  ],
  data: [
    ["background-attachment", ["scroll", "fixed", "inherit"], "scroll", "", "", "", "visual"],
    ["background-color", ["inherit"], "transparent", "", "", "", "visual"],
    ["background-image", ["none", "inherit"], "none", "", "", "", "visual"],
    ["background-position", ["inherit"], "0% 0%", "", "", "refer to the size of the box itself", "visual"],
    ["background-repeat", ["repeat", "repeat-x", "repeat-y", "no-repeat", "inherit"], "repeat", "", "", "", "visual"],
    ["background", ["background-color", "background-image", "background-repeat", "background-attachment", "background-position", "inherit"], "see individual properties", "", "", "allowed on ‘background-position’", "visual"],
    ["border-collapse", ["collapse", "separate", "inherit"], "separate", "‘table’ and ‘inline-table’ elements", true, "", "visual"],
    ["border-color", ["color", "inherit"], "see individual properties", "", "", "", "visual"],
    ["border-spacing", ["inherit"], "0", "‘table’ and ‘inline-table’ elements", true, "", "visual"],
    ["border-style", ["inherit"], "see individual properties", "", "", "", "visual"],
    ["border-top", ["inherit"], "see individual properties", "", "", "", "visual"],
    ["border-bottom", ["inherit"], "see individual properties", "", "", "", "visual"],
    ["border-right", ["inherit"], "see individual properties", "", "", "", "visual"],
    ["border-left", ["inherit"], "see individual properties", "", "", "", "visual"],
    ["border-top-color", ["inherit"], "the value of the ‘color’ property", "", "", "", "visual"],
    ["border-right-color", ["inherit"], "the value of the ‘color’ property", "", "", "", "visual"],
    ["border-bottom-color", ["inherit"], "the value of the ‘color’ property", "", "", "", "visual"],
    ["border-left-color", ["inherit"], "the value of the ‘color’ property", "", "", "", "visual"],
    ["border-top-style", ["inherit"], "none", "", "", "", "visual"],
    ["border-right-style", ["inherit"], "none", "", "", "", "visual"],
    ["border-bottom-style", ["inherit"], "none", "", "", "", "visual"],
    ["border-left-style", ["inherit"], "none", "", "", "", "visual"],
    ["border-top-width", ["inherit"], "medium", "", "", "", "visual"],
    ["border-right-width", ["inherit"], "medium", "", "", "", "visual"],
    ["border-bottom-width", ["inherit"], "medium", "", "", "", "visual"],
    ["border-left-width", ["inherit"], "medium", "", "", "", "visual"],
    ["border-width", ["inherit"], "see individual properties", "", "", "", "visual"],
    ["border", ["inherit"], "see individual properties", "", "", "", "visual"],
    ["bottom", ["auto", "inherit"], "auto", "positioned elements", "", "refer to height of containing block", "visual"],
    ["caption-side", ["top", "bottom", "inherit"], "top", "‘table-caption’ elements", true, "", "visual"],
    ["clear", ["none", "left", "right", "both", "inherit"], "none", "block-level elements", "", "", "visual"],
    ["clip", ["auto", "inherit"], "auto", "absolutely positioned elements", "", "", "visual"],
    ["color", ["inherit"], "depends on user agent", "", true, "", "visual"],
    ["content", ["normal", "none", "open-quote", "close-quote", "no-open-quote", "no-close-quote", "inherit"], "normal", ":before and :after pseudo-elements", "", "", "all"],
    ["counter-increment", ["none", "inherit"], "none", "", "", "", "all"],
    ["counter-reset", ["none", "inherit"], "none", "", "", "", "all"],
    ["cursor", ["auto", "crosshair", "default", "pointer", "move", "e-resize", "ne-resize", "nw-resize", "n-resize", "se-resize", "sw-resize", "s-resize", "w-resize", "text", "wait", "help", "progress", "inherit"], "auto", "", true, "", "visual, interactive"],
    ["direction", ["ltr", "rtl", "inherit"], "ltr", "all elements, but see prose", true, "", "visual"],
    ["display", ["inline", "block", "list-item", "inline-block", "table", "inline-table", "table-row-group", "table-header-group", "table-footer-group", "table-row", "table-column-group", "table-column", "table-cell", "table-caption", "none", "inherit"], "inline", "", "", "", "all"],
    ["empty-cells", ["show", "hide", "inherit"], "show", "‘table-cell’ elements", true, "", "visual"],
    ["float", ["left", "right", "none", "inherit"], "none", "all, but see 9.7", "", "", "visual"],
    ["font-family", ["inherit"], "depends on user agent", "", true, "", "visual"],
    ["font-size", ["inherit"], "medium", "", true, "refer to inherited font size", "visual"],
    ["font-style", ["normal", "italic", "oblique", "inherit"], "normal", "", true, "", "visual"],
    ["font-variant", ["normal", "small-caps", "inherit"], "normal", "", true, "", "visual"],
    ["font-weight", ["normal", "bold", "bolder", "lighter", 100, 200, 300, 400, 500, 600, 700, 800, 900, "inherit"], "normal", "", true, "", "visual"],
    ["font", ["font-style", "font-variant", "font-weight", "font-size", "line-height", "font-family", "caption", "icon", "menu", "message-box", "small-caption", "status-bar", "inherit"], "see individual properties", "", true, "see individual properties", "visual"],
    ["height", ["auto", "inherit"], "auto", "all elements but non-replaced inline elements, table columns, and column groups,", "", "see prose", "visual"],
    ["left", ["auto", "inherit"], "auto", "positioned elements", "", "refer to width of containing block", "visual"],
    ["letter-spacing", ["normal", "inherit"], "normal", "", true, "", "visual"],
    ["line-height", ["normal", "inherit"], "normal", "", true, "refer to the font size of the element itself", "visual"],
    ["list-style-image", ["none", "inherit"], "none", "elements with ‘display: list-item’", true, "", "visual"],
    ["list-style-position", ["inside", "outside", "inherit"], "outside", "elements with ‘display: list-item’", true, "", "visual"],
    ["list-style-type", ["disc", "circle", "square", "decimal", "decimal-leading-zero", "lower-roman", "upper-roman", "lower-greek", "lower-latin", "upper-latin", "armenian", "georgian", "lower-alpha", "upper-alpha", "none", "inherit"], "disc", "elements with ‘display: list-item’", true, "", "visual"],
    ["list-style", ["list-style-type", "list-style-position", "list-style-image", "inherit"], "see individual properties", "elements with ‘display: list-item’", true, "", "visual"],
    ["margin-right margin-left", ["inherit"], "0", "all elements except elements with table display types other than table-caption, table and inline-table", "", "refer to width of containing block", "visual"],
    ["margin-top margin-bottom", ["inherit"], "0", "all elements except elements with table display types other than table-caption, table and inline-table", "", "refer to width of containing block", "visual"],
    ["margin", ["inherit"], "see individual properties", "all elements except elements with table display types other than table-caption, table and inline-table", "", "refer to width of containing block", "visual"],
    ["max-height", ["inherit"], "none", "all elements but non-replaced inline elements, table columns, and column groups", "", "see prose", "visual"],
    ["max-width", ["inherit"], "none", "all elements but non-replaced inline elements, table rows, and row groups", "", "refer to width of containing block", "visual"],
    ["min-height", ["inherit"], "0", "all elements but non-replaced inline elements, table columns, and column groups", "", "see prose", "visual"],
    ["min-width", ["inherit"], "0", "all elements but non-replaced inline elements, table rows, and row groups", "", "refer to width of containing block", "visual"],
    ["opacity", ["inherit"], "1", "all", "", "", "visual"],
    ["orphans", ["inherit"], "2", "block container elements", true, "", "visual, paged"],
    ["outline-color", ["invert", "inherit"], "invert", "", "", "", "visual, interactive"],
    ["outline-style", ["inherit"], "none", "", "", "", "visual, interactive"],
    ["outline-width", ["inherit"], "medium", "", "", "", "visual, interactive"],
    ["outline", ["outline-color", "outline-style", "outline-width", "inherit"], "see individual properties", "", "", "", "visual, interactive"],
    ["overflow", ["visible", "hidden", "scroll", "auto", "inherit"], "visible", "block containers", "", "", "visual"],
    ["padding-top", ["inherit"], "0", "all elements except table-row-group, table-header-group, table-footer-group, table-row, table-column-group and table-column", "", "refer to width of containing block", "visual"],
    ["padding-right", ["inherit"], "0", "all elements except table-row-group, table-header-group, table-footer-group, table-row, table-column-group and table-column", "", "refer to width of containing block", "visual"],
    ["padding-bottom", ["inherit"], "0", "all elements except table-row-group, table-header-group, table-footer-group, table-row, table-column-group and table-column", "", "refer to width of containing block", "visual"],
    ["padding-left", ["inherit"], "0", "all elements except table-row-group, table-header-group, table-footer-group, table-row, table-column-group and table-column", "", "refer to width of containing block", "visual"],
    ["padding", ["inherit"], "see individual properties", "all elements except table-row-group, table-header-group, table-footer-group, table-row, table-column-group and table-column", "", "refer to width of containing block", "visual"],
    ["page-break-after", ["auto", "always", "avoid", "left", "right", "inherit"], "auto", "block-level elements (but see text)", "", "", "visual, paged"],
    ["page-break-before", ["auto", "always", "avoid", "left", "right", "inherit"], "auto", "block-level elements (but see text)", "", "", "visual, paged"],
    ["page-break-inside", ["avoid", "auto", "inherit"], "auto", "block-level elements (but see text)", "", "", "visual, paged"],
    ["position", ["static", "relative", "absolute", "fixed", "inherit"], "static", "", "", "", "visual"],
    ["quotes", ["none", "inherit"], "depends on user agent", "", true, "", "visual"],
    ["right", ["auto", "inherit"], "auto", "positioned elements", "", "refer to width of containing block", "visual"],
    ["table-layout", ["auto", "fixed", "inherit"], "auto", "‘table’ and ‘inline-table’ elements", "", "", "visual"],
    ["text-align", ["left", "right", "center", "justify", "inherit"], "a nameless value that acts as ‘left’ if ‘direction’ is ‘ltr’, ‘right’ if ‘direction’ is ‘rtl’", "block containers", true, "", "visual"],
    ["text-decoration", ["none", "underline", "overline", "line-through", "blink", "inherit"], "none", "", "no (see prose)", "", "visual"],
    ["text-indent", ["inherit"], "0", "block containers", true, "refer to width of containing block", "visual"],
    ["text-transform", ["capitalize", "uppercase", "lowercase", "none", "inherit"], "none", "", true, "", "visual"],
    ["top", ["auto", "inherit"], "auto", "positioned elements", "", "refer to height of containing block", "visual"],
    ["unicode-bidi", ["normal", "embed", "bidi-override", "inherit"], "normal", "all elements, but see prose", "", "", "visual"],
    ["vertical-align", ["baseline", "sub", "super", "top", "text-top", "middle", "bottom", "text-bottom", "inherit"], "baseline", "inline-level and ‘table-cell’ elements", "", "refer to the ‘line-height’ of the element itself", "visual"],
    ["visibility", ["visible", "hidden", "collapse", "inherit"], "visible", "", true, "", "visual"],
    ["white-space", ["normal", "pre", "nowrap", "pre-wrap", "pre-line", "inherit"], "normal", "", true, "", "visual"],
    ["widows", ["inherit"], "2", "block container elements", true, "", "visual, paged"],
    ["width", ["auto", "inherit"], "auto", "all elements but non-replaced inline elements, table rows, and row groups", "", "refer to width of containing block", "visual"],
    ["word-spacing", ["normal", "inherit"], "normal", "", true, "", "visual"],
    ["z-index", ["auto", "inherit"], "auto", "positioned elements", "", "", "visual"],
    ["accent-color", ["auto", "<color>", "inherit"], "auto", "", true, "", "visual, interactive"],
    ["align-content", ["normal", "flex-start", "flex-end", "center", "space-between", "space-around", "space-evenly", "stretch", "start", "end", "baseline", "inherit"], "normal", "multi-line flex containers, grid containers", "", "", "visual"],
    ["align-items", ["normal", "stretch", "flex-start", "flex-end", "center", "start", "end", "self-start", "self-end", "baseline", "inherit"], "normal", "flex containers, grid containers", "", "", "visual"],
    ["align-self", ["auto", "normal", "stretch", "flex-start", "flex-end", "center", "start", "end", "self-start", "self-end", "baseline", "inherit"], "auto", "flex items, grid items", "", "", "visual"],
    ["animation", ["animation-name", "animation-duration", "animation-timing-function", "animation-delay", "animation-iteration-count", "animation-direction", "animation-fill-mode", "animation-play-state", "inherit"], "see individual properties", "", "", "", "visual, interactive"],
    ["animation-delay", ["<time>", "inherit"], "0s", "", "", "", "visual, interactive"],
    ["animation-direction", ["normal", "reverse", "alternate", "alternate-reverse", "inherit"], "normal", "", "", "", "visual, interactive"],
    ["animation-duration", ["<time>", "inherit"], "0s", "", "", "", "visual, interactive"],
    ["animation-fill-mode", ["none", "forwards", "backwards", "both", "inherit"], "none", "", "", "", "visual, interactive"],
    ["animation-iteration-count", ["<number>", "infinite", "inherit"], "1", "", "", "", "visual, interactive"],
    ["animation-name", ["none", "<keyframes-name>", "inherit"], "none", "", "", "", "visual, interactive"],
    ["animation-play-state", ["running", "paused", "inherit"], "running", "", "", "", "visual, interactive"],
    ["animation-timing-function", ["ease", "linear", "ease-in", "ease-out", "ease-in-out", "step-start", "step-end", "steps()", "cubic-bezier()", "inherit"], "ease", "", "", "", "visual, interactive"],
    ["appearance", ["none", "auto", "menulist-button", "textfield", "inherit"], "auto", "", "", "", "visual"],
    ["aspect-ratio", ["auto", "<ratio>", "inherit"], "auto", "all elements except inline boxes and internal ruby or table boxes", "", "", "visual"],
    ["backdrop-filter", ["none", "<filter-function-list>", "inherit"], "none", "", "", "", "visual"],
    ["background-clip", ["border-box", "padding-box", "content-box", "text", "inherit"], "border-box", "", "", "", "visual"],
    ["background-origin", ["border-box", "padding-box", "content-box", "inherit"], "padding-box", "", "", "", "visual"],
    ["background-size", ["auto", "cover", "contain", "<length>", "<percentage>", "inherit"], "auto", "", "", "refer to background positioning area", "visual"],
    ["block-size", ["<length>", "<percentage>", "auto", "inherit"], "auto", "", "", "refer to containing block", "visual"],
    ["border-image", ["border-image-source", "border-image-slice", "border-image-width", "border-image-outset", "border-image-repeat", "inherit"], "see individual properties", "", "", "refer to size of border image area", "visual"],
    ["border-image-outset", ["<length>", "<number>", "inherit"], "0", "", "", "", "visual"],
    ["border-image-repeat", ["stretch", "repeat", "round", "space", "inherit"], "stretch", "", "", "", "visual"],
    ["border-image-slice", ["<number>", "<percentage>", "fill", "inherit"], "100%", "", "", "refer to size of border image", "visual"],
    ["border-image-source", ["none", "<image>", "inherit"], "none", "", "", "", "visual"],
    ["border-image-width", ["<length>", "<percentage>", "<number>", "auto", "inherit"], "1", "", "", "refer to width or height of border image area", "visual"],
    ["border-radius", ["<length>", "<percentage>", "inherit"], "0", "", "", "refer to corresponding dimension of border box", "visual"],
    ["border-top-left-radius", ["<length>", "<percentage>", "inherit"], "0", "", "", "refer to corresponding dimension of border box", "visual"],
    ["border-top-right-radius", ["<length>", "<percentage>", "inherit"], "0", "", "", "refer to corresponding dimension of border box", "visual"],
    ["border-bottom-right-radius", ["<length>", "<percentage>", "inherit"], "0", "", "", "refer to corresponding dimension of border box", "visual"],
    ["border-bottom-left-radius", ["<length>", "<percentage>", "inherit"], "0", "", "", "refer to corresponding dimension of border box", "visual"],
    ["box-shadow", ["none", "<shadow>", "inherit"], "none", "", "", "", "visual"],
    ["box-sizing", ["content-box", "border-box", "inherit"], "content-box", "all elements that accept width or height", "", "", "visual"],
    ["caret-color", ["auto", "<color>", "inherit"], "auto", "", true, "", "visual, interactive"],
    ["column-count", ["<integer>", "auto", "inherit"], "auto", "non-replaced block-level elements (except table elements), table cells, inline-block elements", "", "", "visual"],
    ["column-fill", ["auto", "balance", "balance-all", "inherit"], "balance", "multicol elements", "", "", "visual"],
    ["column-gap", ["<length>", "<percentage>", "normal", "inherit"], "normal", "multi-column, flex, and grid containers", "", "refer to inline size of content area", "visual"],
    ["column-rule", ["column-rule-width", "column-rule-style", "column-rule-color", "inherit"], "see individual properties", "", "", "", "visual"],
    ["column-rule-color", ["<color>", "inherit"], "currentColor", "", "", "", "visual"],
    ["column-rule-style", ["<border-style>", "inherit"], "none", "", "", "", "visual"],
    ["column-rule-width", ["<length>", "inherit"], "medium", "", "", "", "visual"],
    ["column-span", ["none", "all", "inherit"], "none", "in-flow block-level elements", "", "", "visual"],
    ["column-width", ["<length>", "auto", "inherit"], "auto", "non-replaced block-level elements (except table elements), table cells, inline-block elements", "", "", "visual"],
    ["columns", ["column-width", "column-count", "inherit"], "see individual properties", "non-replaced block-level elements (except table elements), table cells, inline-block elements", "", "", "visual"],
    ["contain", ["none", "strict", "content", "size", "inline-size", "layout", "style", "paint", "inherit"], "none", "", "", "", "all"],
    ["filter", ["none", "<filter-function-list>", "inherit"], "none", "", "", "", "visual"],
    ["flex", ["flex-grow", "flex-shrink", "flex-basis", "none", "auto", "inherit"], "see individual properties", "flex items", "", "", "visual"],
    ["flex-basis", ["auto", "content", "<length>", "<percentage>", "inherit"], "auto", "flex items", "", "refer to flex container inner main size", "visual"],
    ["flex-direction", ["row", "row-reverse", "column", "column-reverse", "inherit"], "row", "flex containers", "", "", "visual"],
    ["flex-flow", ["flex-direction", "flex-wrap", "inherit"], "see individual properties", "flex containers", "", "", "visual"],
    ["flex-grow", ["<number>", "inherit"], "0", "flex items", "", "", "visual"],
    ["flex-shrink", ["<number>", "inherit"], "1", "flex items", "", "", "visual"],
    ["flex-wrap", ["nowrap", "wrap", "wrap-reverse", "inherit"], "nowrap", "flex containers", "", "", "visual"],
    ["gap", ["row-gap", "column-gap", "inherit"], "see individual properties", "multi-column, flex, and grid containers", "", "refer to corresponding dimension of content area", "visual"],
    ["grid", ["grid-template-rows", "grid-template-columns", "grid-template-areas", "grid-auto-rows", "grid-auto-columns", "grid-auto-flow", "inherit"], "see individual properties", "grid containers", "", "", "visual"],
    ["grid-area", ["<grid-line>", "auto", "inherit"], "auto", "grid items", "", "", "visual"],
    ["grid-auto-columns", ["<track-size>", "auto", "inherit"], "auto", "grid containers", "", "refer to corresponding dimension of content area", "visual"],
    ["grid-auto-flow", ["row", "column", "dense", "row dense", "column dense", "inherit"], "row", "grid containers", "", "", "visual"],
    ["grid-auto-rows", ["<track-size>", "auto", "inherit"], "auto", "grid containers", "", "refer to corresponding dimension of content area", "visual"],
    ["grid-column", ["grid-column-start", "grid-column-end", "inherit"], "see individual properties", "grid items", "", "", "visual"],
    ["grid-column-end", ["<grid-line>", "auto", "inherit"], "auto", "grid items", "", "", "visual"],
    ["grid-column-start", ["<grid-line>", "auto", "inherit"], "auto", "grid items", "", "", "visual"],
    ["grid-row", ["grid-row-start", "grid-row-end", "inherit"], "see individual properties", "grid items", "", "", "visual"],
    ["grid-row-end", ["<grid-line>", "auto", "inherit"], "auto", "grid items", "", "", "visual"],
    ["grid-row-start", ["<grid-line>", "auto", "inherit"], "auto", "grid items", "", "", "visual"],
    ["grid-template", ["grid-template-rows", "grid-template-columns", "grid-template-areas", "none", "inherit"], "see individual properties", "grid containers", "", "", "visual"],
    ["grid-template-areas", ["none", "<string>+", "inherit"], "none", "grid containers", "", "", "visual"],
    ["grid-template-columns", ["none", "<track-list>", "<auto-track-list>", "inherit"], "none", "grid containers", "", "refer to corresponding dimension of content area", "visual"],
    ["grid-template-rows", ["none", "<track-list>", "<auto-track-list>", "inherit"], "none", "grid containers", "", "refer to corresponding dimension of content area", "visual"],
    ["hyphens", ["none", "manual", "auto", "inherit"], "manual", "", true, "", "visual"],
    ["inline-size", ["<length>", "<percentage>", "auto", "inherit"], "auto", "", "", "refer to containing block", "visual"],
    ["inset", ["<length>", "<percentage>", "auto", "inherit"], "auto", "positioned elements", "", "refer to size of containing block", "visual"],
    ["isolation", ["auto", "isolate", "inherit"], "auto", "", "", "", "visual"],
    ["justify-content", ["normal", "flex-start", "flex-end", "center", "space-between", "space-around", "space-evenly", "start", "end", "left", "right", "stretch", "inherit"], "normal", "flex containers, grid containers, multi-column containers", "", "", "visual"],
    ["justify-items", ["normal", "stretch", "start", "end", "center", "left", "right", "baseline", "legacy", "inherit"], "legacy", "grid containers", "", "", "visual"],
    ["justify-self", ["auto", "normal", "stretch", "start", "end", "center", "left", "right", "baseline", "inherit"], "auto", "grid items and absolutely-positioned boxes", "", "", "visual"],
    ["max-block-size", ["<length>", "<percentage>", "none", "inherit"], "none", "", "", "refer to containing block", "visual"],
    ["max-inline-size", ["<length>", "<percentage>", "none", "inherit"], "none", "", "", "refer to containing block", "visual"],
    ["min-block-size", ["<length>", "<percentage>", "auto", "inherit"], "auto", "", "", "refer to containing block", "visual"],
    ["min-inline-size", ["<length>", "<percentage>", "auto", "inherit"], "auto", "", "", "refer to containing block", "visual"],
    ["mix-blend-mode", ["normal", "multiply", "screen", "overlay", "darken", "lighten", "color-dodge", "color-burn", "hard-light", "soft-light", "difference", "exclusion", "hue", "saturation", "color", "luminosity", "inherit"], "normal", "", "", "", "visual"],
    ["object-fit", ["fill", "contain", "cover", "none", "scale-down", "inherit"], "fill", "replaced elements", "", "", "visual"],
    ["object-position", ["<position>", "inherit"], "50% 50%", "replaced elements", "", "refer to width and height of element", "visual"],
    ["order", ["<integer>", "inherit"], "0", "flex items, grid items", "", "", "visual"],
    ["overflow-wrap", ["normal", "break-word", "anywhere", "inherit"], "normal", "", true, "", "visual"],
    ["overflow-x", ["visible", "hidden", "scroll", "auto", "clip", "inherit"], "visible", "block containers, flex containers, grid containers", "", "", "visual"],
    ["overflow-y", ["visible", "hidden", "scroll", "auto", "clip", "inherit"], "visible", "block containers, flex containers, grid containers", "", "", "visual"],
    ["place-content", ["align-content", "justify-content", "inherit"], "see individual properties", "multi-line flex containers, grid containers", "", "", "visual"],
    ["place-items", ["align-items", "justify-items", "inherit"], "see individual properties", "flex containers, grid containers", "", "", "visual"],
    ["place-self", ["align-self", "justify-self", "inherit"], "see individual properties", "flex items, grid items", "", "", "visual"],
    ["pointer-events", ["auto", "none", "visiblePainted", "visibleFill", "visibleStroke", "visible", "painted", "fill", "stroke", "all", "inherit"], "auto", "", true, "", "visual"],
    ["resize", ["none", "both", "horizontal", "vertical", "block", "inline", "inherit"], "none", "elements with overflow other than visible", "", "", "visual, interactive"],
    ["row-gap", ["<length>", "<percentage>", "normal", "inherit"], "normal", "multi-column, flex, and grid containers", "", "refer to block size of content area", "visual"],
    ["scroll-behavior", ["auto", "smooth", "inherit"], "auto", "scroll containers", "", "", "visual, interactive"],
    ["scroll-snap-align", ["none", "start", "end", "center", "inherit"], "none", "", "", "", "visual, interactive"],
    ["scroll-snap-type", ["none", "x", "y", "block", "inline", "both", "mandatory", "proximity", "inherit"], "none", "scroll containers", "", "", "visual, interactive"],
    ["tab-size", ["<integer>", "<length>", "inherit"], "8", "block containers", true, "", "visual"],
    ["text-overflow", ["clip", "ellipsis", "<string>", "inherit"], "clip", "block containers", "", "", "visual"],
    ["text-shadow", ["none", "<shadow>", "inherit"], "none", "", true, "", "visual"],
    ["transform", ["none", "<transform-list>", "inherit"], "none", "transformable elements", "", "refer to size of reference box", "visual"],
    ["transform-origin", ["<length>", "<percentage>", "left", "center", "right", "top", "bottom", "inherit"], "50% 50% 0", "transformable elements", "", "refer to size of reference box", "visual"],
    ["transition", ["transition-property", "transition-duration", "transition-timing-function", "transition-delay", "inherit"], "see individual properties", "", "", "", "visual, interactive"],
    ["transition-delay", ["<time>", "inherit"], "0s", "", "", "", "visual, interactive"],
    ["transition-duration", ["<time>", "inherit"], "0s", "", "", "", "visual, interactive"],
    ["transition-property", ["none", "all", "<custom-ident>", "inherit"], "all", "", "", "", "visual, interactive"],
    ["transition-timing-function", ["ease", "linear", "ease-in", "ease-out", "ease-in-out", "step-start", "step-end", "steps()", "cubic-bezier()", "inherit"], "ease", "", "", "", "visual, interactive"],
    ["user-select", ["auto", "text", "none", "contain", "all", "inherit"], "auto", "", "", "", "visual"],
    ["will-change", ["auto", "scroll-position", "contents", "<custom-ident>", "inherit"], "auto", "", "", "", "all"],
    ["word-break", ["normal", "keep-all", "break-all", "break-word", "inherit"], "normal", "", true, "", "visual"],
    ["word-wrap", ["normal", "break-word", "anywhere", "inherit"], "normal", "", true, "", "visual"],
    ["writing-mode", ["horizontal-tb", "vertical-rl", "vertical-lr", "inherit"], "horizontal-tb", "all elements except table row groups, table column groups, table rows, and table columns", "", "", "visual"],
  ],
}
