export const selectors = {
  structure: ['Pattern', 'Meaning', 'Level'],
  data: [
    ['*', 'any element', 2],
    ['E', 'an element of type E', 1],
    ['E#myid', 'an E element with ID equal to "myid".', 1],
    ['E.warning', 'an E element whose class is "warning" (the document language specifies how class is determined).', 1],
    ['E F', 'an F element descendant of an E element', 1],
    ['E > F', 'an F element child of an E element', 2],
    ['E + F', 'an F element immediately preceded by an E element', 2],
    ['E ~ F', 'an F element preceded by an E element', 3],
    ['E[foo]', 'an E element with a "foo" attribute', 2],
    ['E[foo="bar"]', 'an E element whose "foo" attribute value is exactly equal to "bar"', 2],
    ['E[foo~="bar"]', 'an E element whose "foo" attribute value is a list of whitespace-separated values, one of which is exactly equal to "bar"', 2],
    ['E[foo^="bar"]', 'an E element whose "foo" attribute value begins exactly with the string "bar"', 3],
    ['E[foo$="bar"]', 'an E element whose "foo" attribute value ends exactly with the string "bar"', 3],
    ['E[foo*="bar"]', 'an E element whose "foo" attribute value contains the substring "bar"', 3],
    ['E[foo|="en"]', 'an E element whose "foo" attribute has a hyphen-separated list of values beginning (from the left) with "en"', 2],
    ['E:root', 'an E element, root of the document', 3],
    ['E:nth-child(n)', 'an E element, the n-th child of its parent', 3],
    ['E:nth-last-child(n)', 'an E element, the n-th child of its parent, counting from the last one', 3],
    ['E:nth-of-type(n)', 'an E element, the n-th sibling of its type', 3],
    ['E:nth-last-of-type(n)', 'an E element, the n-th sibling of its type, counting from the last one', 3],
    ['E:first-child', 'an E element, first child of its parent', 2],
    ['E:last-child', 'an E element, last child of its parent', 3],
    ['E:first-of-type', 'an E element, first sibling of its type', 3],
    ['E:last-of-type', 'an E element, last sibling of its type', 3],
    ['E:only-child', 'an E element, only child of its parent', 3],
    ['E:only-of-type', 'an E element, only sibling of its type', 3],
    ['E:empty', 'an E element that has no children (including text nodes)', 3],
    ['E:link', 'an E element being the source anchor of a hyperlink of which the target is not yet visited (:link)', 1],
    ['E:visited', 'an E element being the source anchor of a hyperlink of which the target is already visited (:visited)', 1],
    ['E:active', 'an E element during certain user actions', '1, 2'],
    ['E:hover', 'an E element during certain user actions', '1, 2'],
    ['E:focus', 'an E element during certain user actions', '1, 2'],
    ['E:target', 'an E element being the target of the referring URI', 3],
    ['E:lang(fr)', 'an element of type E in language "fr" (the document language specifies how language is determined)', 2],
    ['E:enabled', 'a user interface element E which is enabled or disabled', 3],
    ['E:disabled', 'a user interface element E which is enabled or disabled', 3],
    ['E:checked', 'a user interface element E which is checked (for instance a radio-button or checkbox)', 3],
    ['E:not(s)', 'an E element that does not match simple selector s', 3],
    ['E::first-line', 'the first formatted line of an E element', 1],
    ['E::first-letter', 'the first formatted letter of an E element', 1],
    ['E::before', 'generated content before an E element', 2],
    ['E::after', 'generated content after an E element', 2],
    ['E[foo="bar" i]', 'an E element whose "foo" attribute value is exactly "bar", matched case-insensitively', 4],
    ['E[foo="bar" s]', 'an E element whose "foo" attribute value is exactly "bar", matched case-sensitively', 4],
    ['E || F', 'an F element that represents a cell in a grid/table belonging to a column represented by an E element', 4],
    ['E F G', 'a G element that is a descendant of an F element that is a descendant of an E element (descendant combinator)', 1],
    ['E:any-link', 'an E element being the source anchor of a hyperlink (visited or unvisited)', 4],
    ['E:default', 'a user interface element E that is the default among a set of similar elements', 3],
    ['E:defined', 'an E element that is defined (built-in or registered custom element)', 4],
    ['E:dir(ltr)', 'an E element whose directionality is left-to-right', 4],
    ['E:dir(rtl)', 'an E element whose directionality is right-to-left', 4],
    ['E:focus-visible', 'an E element that has focus and the user agent determines focus should be visible', 4],
    ['E:focus-within', 'an E element that has focus or contains a focused descendant', 4],
    ['E:fullscreen', 'an E element that is currently being presented in fullscreen mode', 4],
    ['E:has(F)', 'an E element that contains at least one F element matching the relative selector', 4],
    ['E:host', 'an E element that is the shadow host of the current shadow tree', 4],
    ['E:host(s)', 'a shadow host E matching the compound selector s', 4],
    ['E:host-context(s)', 'a shadow host E whose ancestor matches selector s', 4],
    ['E:in-range', 'an E element whose value is in-range (e.g. an input with min/max constraints)', 3],
    ['E:out-of-range', 'an E element whose value is out-of-range', 3],
    ['E:indeterminate', 'a user interface element E that is in an indeterminate state', 3],
    ['E:is(s1, s2)', 'an E element matching any of the selectors s1, s2, …', 4],
    ['E:lang(zh, *-hant)', 'an E element tagged with any of the listed languages or language ranges', 4],
    ['E:not(s1, s2)', 'an E element that does not match any of the selectors s1, s2, …', 4],
    ['E:nth-child(n of S)', 'an E element, the n-th child of its parent matching selector S', 4],
    ['E:nth-last-child(n of S)', 'an E element, the n-th child from the end matching selector S', 4],
    ['E:optional', 'a user input element E that is not required', 3],
    ['E:required', 'a user input element E that is required', 3],
    ['E:placeholder-shown', 'an input element E currently displaying placeholder text', 4],
    ['E:read-only', 'a user interface element E that is not user-alterable', 3],
    ['E:read-write', 'a user interface element E that is user-alterable', 3],
    ['E:scope', 'an E element that is a reference point for matching (the scope root)', 4],
    ['E:valid', 'an E element whose contents successfully validate', 3],
    ['E:invalid', 'an E element whose contents fail to validate', 3],
    ['E:where(s1, s2)', 'an E element matching any of the selectors s1, s2, … (zero specificity)', 4],
    ['E::backdrop', 'the backdrop pseudo-element rendered behind an E element in the top layer', 4],
    ['E::cue', 'WebVTT cues within a media element E', 4],
    ['E::file-selector-button', 'the button generated inside a file input E', 4],
    ['E::marker', 'the marker box of a list item E (bullet or number)', 3],
    ['E::part(name)', 'a shadow DOM part of E exposed via the "part" attribute named "name"', 4],
    ['E::placeholder', 'the placeholder text of an input E', 4],
    ['E::selection', 'the portion of E currently selected/highlighted by the user', 4],
    ['E::slotted(s)', 'an element matching s that is slotted into the shadow tree of E', 4],
  ],
}
